name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yaml
    with:
      account_id: '{{aws-account-id}}'
      bucket_name: '{{aws-bucket-name}}'
    secrets:
      npm_github_token: ${{'{'}}{ secrets.NPM_GITHUB_TOKEN }}
