name: DEV Environment Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  build_and_deploy:
    uses: nax-platform/github-actions/.github/workflows/build-deploy-front-end-{{delivery-type}}.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
      GITHUB_TOKEN: ${{'{'}}{ secrets.NPM_GITHUB_TOKEN }}