on:
  push:
    branches:
      - main

name: "Docs: Deploy Documentation"
run-name: Deploy Documentation

jobs:
  deploy_docs:
    uses: nax-platform/github-actions/.github/workflows/build-deploy-front-end-docs.yaml@main
