name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    uses: nax-platform/github-actions/.github/workflows/test-front-end.yaml@main
    secrets:
      NPM_GITHUB_TOKEN: ${{'{'}}{ secrets.NPM_GITHUB_TOKEN }}
